### ISSUE TITLE
Mac M1 stuck loading screen

### ISSUE THREAD

**Issue by donsimn** [105-Code/SFS-Modloader#6]
I am trying to run modloader on my M1 macbook air. I am using the latest OSX, SFS and Modloader version. I also verified that i installed the modloader properly with help of the SFS Discord.

When im starting SFS, it's just suck at a blackscreen and with the spinning loading cursor. It's not responding.

**Comment by dani0105** [comment]
if you have the beta version of SFS some mods throw errors, you should also update the modloader version
