### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by cr1spyapple** [105-Code/SFS-Modloader#7]
I can't get the modloader to work on Linux, are there any plans for Linux support?

**Comment by dani0105** [comment]
@DelightedDuck 
modloader should work on Linux, but it needs another doorstop library. I have this linux version of modloader, but I need to test it to see if it loads, maybe it won't run, so you'll need to edit run.sh. I will attach some useful links.

[bepinex](https://docs.bepinex.dev/articles/user_guide/installation/index.html?tabs=tabid-nix)
[doorstopUnix](https://github.com/NeighTools/UnityDoorstop.Unix/releases/tag/v1.5.1.0)

modloder linux version:
[modloader-linux.zip](https://github.com/105-Code/SFS-Modloader/files/8943548/modloader-linux.zip)

if you get it running I appreciate you passing the run.sh it works fine

**Comment by Okirshen** [comment]
this assumes the game is native and SFS sadly isnt native to linux so it doesnt work. Me and ASoD failed to run it on proton.

**Comment by cr1spyapple** [comment]
> @DelightedDuck modloader should work on Linux, but it needs another doorstop library. I have this linux version of modloader, but I need to test it to see if it loads, maybe it won't run, so you'll need to edit run.sh. I will attach some useful links.
> 
> [bepinex](https://docs.bepinex.dev/articles/user_guide/installation/index.html?tabs=tabid-nix) [doorstopUnix](https://github.com/NeighTools/UnityDoorstop.Unix/releases/tag/v1.5.1.0)
> 
> modloder linux version: [modloader-linux.zip](https://github.com/105-Code/SFS-Modloader/files/8943548/modloader-linux.zip)
> 
> if you get it running I appreciate you passing the run.sh it works fine

Sadly as @Okirshen said it this doesn't work on the Windows version of SFS. I will wait for the linux port and try again.
