### ISSUE TITLE
Crashed on MacOS

### ISSUE THREAD

**Issue by Little-Red-Stone** [105-Code/SFS-Modloader#8]
I followed the steps on the wiki, but the game crashed after running "run.sh"
（I don't speak English, so the above is machine translated）

**Comment by Little-Red-Stone** [comment]
like this
https://user-images.githubusercontent.com/73737596/178648641-8f6d2c26-9772-41d9-a409-eb15a69747db.mp4

ps: Opening with steam script will also crash

**Comment by dani0105** [comment]
in the recent update Mac stopped working, I recommend installing the new mod loader which is implemented natively in the game (it's the same code and many mods have already been ported). You can find the link to update on discod in the #public-beta channel
