### ISSUE TITLE
Console doesn't show up

### ISSUE THREAD

**Issue by Snuyyz** [105-Code/SFS-Modloader#9]
So, I've installed it along the instructions but when, I launch SFS I have only MODS and there's no console.
What I do?
![Spaceflight Simulator 21 07 2022 14_46_34](https://user-images.githubusercontent.com/38729580/180196176-9bede526-1f58-4500-87ba-93f44e24a7c4.png)

**Comment by dani0105** [comment]
the console should show with F1
